README.md, lib/opentracing.rb, lib/opentracing/tracer.rb, test/tracer_test.rb
Basically:
- `#inject` comments were OOD
- `#extract` semantics were OOD (took an operation name, returned a Span rather than SpanContext)
- format comments were incomplete and/or misleading
There is still more left in the OT spec beyond what's here (namely support for FollowsFrom references), but I've focused only on getting rid of API surface area that deviates from the OT spec. (I.e., future compliance changes would be backwards-compatible)
=> Bring OpenTracing lib into compliance with OT spec

lib/opentracing/span.rb
Previously used required named arguments (without defaults)
which was added in Ruby 2.1
=> Span.initialize: Use old-style params for Ruby 2.0

lib/opentracing.rb, test/opentracing_test.rb, test/span_test.rb
Currently only OpenTracing.start_span is forwarded.
OpenTracing::Trace#inject and #extract are very similar. Forwarding
these should make using OpenTracing library a bit more convenient.
=> Forward inject and extract calls to global tracer

lib/opentracing/tracer.rb
Make it explcit that both Span and SpanContext can be provided for
child_of parameter. Previously had to read the full description to
understand that Span is also allowed.
=> Improve Tracer#start_span documentation

lib/opentracing.rb, lib/opentracing/reference.rb, lib/opentracing/tracer.rb, test/reference_test.rb, test/tracer_test.rb
Most of the documentation is from
https://github.com/opentracing/opentracing-go/blob/master/tracer.go#L169
@bhs I noticed that all libraries have a convenience option `childOf` but I don't think any had `followsFrom`. Instead they used `references`. Is there a reason for that?
I currently added it as a `follows_from` option similarly to the `child_of` option.
=> Add follows_from option to Tracer#start_span

README.md
Ruby's `Net::HTTP#new` [takes a server address](https://docs.ruby-lang.org/en/2.0.0/Net/HTTP.html#method-c-new), not a full URI. 
From the docs:
> The address should be a DNS hostname or IP address, the port is the port the server operates on. If no port is given the default port for HTTP or HTTPS is used.
=> Fixing serialization example

lib/opentracing.rb, test/opentracing_test.rb
Currently this gem boots with the global tracer (`OpenTracing.global_tracer`) uninitialized (set to `nil`).  
This causes applications with OpenTracing calls but without a selected tracer to crash.
This scenario of not having a real tracer can occur for various reasons:
1. Removal or disabling of a tracer to debug related or unrelated issues.
2. An application that has no direct OpenTracing calls but include a library or gem (e.g. opentracing-contrib) that do
This also follows the other language implementations that set the global tracer to the no-op tracer by default ([Python](https://github.com/opentracing/opentracing-python/blob/master/opentracing/__init__.py#L39), [Go](https://github.com/opentracing/opentracing-go/blob/master/globaltracer.go#L4) & …
=> Assure that global_tracer is not nil; default to no-op tracer

README.md
Unless someone else is excited about supporting Ruby versions < 2, going to clarify that this supports Ruby 2.0+. Ruby 2.0 was released in early 2013.
=> Clarify Ruby version support

lib/opentracing/span.rb, test/span_test.rb, test/test_helper.rb, test/tracer_test.rb
PR for issue #22 
@itsderek23 @mwear I moved the `assert_warn` method to `test_helper` for sharing.  There is a [structured_warnings](https://github.com/schmidt/structured_warnings) gem with more support warning methods.  I don't think we need the gem for now but I can include it in the PR if that makes sense.
=> Deprecate log; add log_kv

CHANGELOG.md, lib/opentracing.rb, lib/opentracing/scope.rb, lib/opentracing/scope_manager.rb, lib/opentracing/tracer.rb, lib/opentracing/version.rb, test/reference_test.rb, test/scope_manager_test.rb, test/scope_test.rb, test/tracer_test.rb
I was reviewing the Scope API implemented in v0.31.0 of the [opentracing-java](https://github.com/opentracing/opentracing-java) project and decided to try and adapt it for Ruby. I added implementations of `Scope` and `ScopeManager` and updated the Tracer class with methods: `start_active` and `start`. This work was based heavily on the following:
* https://github.com/opentracing/opentracing-java
* https://github.com/opentracing/opentracing-python/pull/64
The work here is just a starting point. I'd be happy to address any questions, comments, or suggestions.
=> Adapt Scope API for Ruby

CHANGELOG.md, lib/opentracing.rb, lib/opentracing/scope.rb, lib/opentracing/scope_manager.rb, lib/opentracing/span.rb, lib/opentracing/tracer.rb, lib/opentracing/version.rb, test/scope_manager_test.rb, test/scope_test.rb, test/span_test.rb, test/test_helper.rb, test/tracer_test.rb
This merges #21 and #23 into a `0.4.0` branch. 
This shouldn't add any breaking changes, but I haven't tested with an actual tracer.
Released as `0.4.0.rc1` on RubyGems.
Anyone with a real-world implementation of `opentracing-ruby` mind verifying this works as desired?
=> v0.4.0 Release

lib/opentracing.rb, test/opentracing_test.rb
In version 0.3.2 there were delgators defined on the `OpenTracing` module that would forward to their respective methods on the global tracer. In 0.4.0 two new methods were added to the `Tracer` API, but the delegators were not added to the `OpenTracing` module. This PR fixes that oversight.
=> Fix global tracer delegators

lib/opentracing.rb, test/opentracing_test.rb
This method was added based on the excellent [suggestion](https://github.com/opentracing/opentracing-ruby/pull/29#discussion_r180877729) from @indrekj  on #29.
It's a common task to have to access the currently active `Span` and it's slightly cumbersome to type: `OpenTracing.scope_manager.active.span`. With this convenience method, the currently active `Span` will be accessible through `OpenTracing.active_span`.
=> Add active_span convenience method to OpenTracing module

test/opentracing_test.rb
When working on #30, I noticed that we were not verifying expectations set on mocks. This PR fixes that. I also renamed a poorly named mock from a recently written test. The mock represents the scope_manager, but was named `scope`. I renamed it to `scope_manager` for clarity.
=> Verify expectations on mocks in opentracing_test

lib/opentracing.rb, lib/opentracing/tracer.rb, opentracing.gemspec, test/opentracing_test.rb, test/tracer_test.rb
Previously it was only defined in OpenTracing module. Tracer#active_span
is also defined in opentracing python and java. Define it here as well
and make OpenTracing to delegate to Tracer instead.
This is useful when Tracer object is being passed around and OpenTracing
module is not used directly.
This is a backwards compatible change.
=> Add active_span method to Tracer

README.md
While checking this README I realized that the current link for terminology was broken. I have changed the link to point to `documentation overview` where all definitions about Spans, Scopes, Threading, etc. can be found.
I also took the chance to change protocol from http to https in the main project's link.
=> Improve and fix README opentracing.io links

CHANGELOG.md, lib/opentracing/version.rb
This PR updates the changelog and bumps the version in preparation for 0.4.2 release to address #37. The complete list of changes is below:
* Update opentracing.io links and scheme on README ([#38](https://github.com/opentracing/opentracing-ruby/pull/38))
* Add active_span method to Tracer ([#34](https://github.com/opentracing/opentracing-ruby/pull/34))
=> Prepare for 0.4.2 release

CHANGELOG.md, lib/opentracing/version.rb, opentracing.gemspec
While building the v0.4.2 gem release there were several warnings regarding open ended dependencies. For example:
```
WARNING:  open-ended dependency on simplecov (>= 0, development) is not recommended
if simplecov is semantically versioned, use:
add_development_dependency 'simplecov', '~> 0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
```
My first attempt to fix this issue was [e588d96](https://github.com/opentracing/opentracing-ruby/commit/e588d96d3d102ac06727339250fa5c3dc6fd5e3b) which was released as 0.4.2. Unfortunately, the bundler versioning broke the [build](https://travis-ci.org/opentracing/opentracing-ruby/builds/444695333. While there isn't technically anything wrong with the ruby code, the officially released gem should have a passing build.
I …
=> Version dependencies / Release 0.4.3

lib/opentracing/span.rb
It was originally accepting kwargs but the documentation says any Hash object would be sufficient. There is no reason to restrict it to only accept hash with symbol keys.
**Current Behaviour:**
It raises `ArgumentError: wrong number of arguments` if you try to give it hash with keys other than symbol.
**Expected/Fixed Behaviour:**
It shouldn't raise exception for hash objects with keys other than symbol.
=> Fix documentation of Span#log and Span#log_kv methods

CHANGELOG.md, lib/opentracing/tracer.rb, test/tracer_test.rb
[#41](https://github.com/opentracing/opentracing-ruby/issues/41) has been open for comment for quite some time, and all feedback has been in favor of the suggested changes. While discussing [#41](https://github.com/opentracing/opentracing-ruby/issues/41) there was interest in addressing [#13](https://github.com/opentracing/opentracing-ruby/issues/13) to provide symmetry between the `Tracer#start_span` and `Tracer#start_active_span` APIs. This PR addresses both [#13](https://github.com/opentracing/opentracing-ruby/issues/13) and [#41](https://github.com/opentracing/opentracing-ruby/issues/41).
`Tracer#start_span` now accepts an optional block. When a block is given, it returns the block's return value, otherwise it returns the newly-created span. See …
=> Address issues #13 and #41

CHANGELOG.md, lib/opentracing/version.rb
This PR updates the changelog and version for the 0.5.0 release. Below is a summary of the changes:
* Tracer#start_span now accepts an optional block. When passed a block, it returns the block's return value, otherwise it returns the newly-created span ([#45](https://github.com/opentracing/opentracing-ruby/pull/45)). See [Issue #13](https://github.com/opentracing/opentracing-ruby/issues/13).
* When passed an optional block, Tracer#start_active_span returns the block's return value, otherwise it returns the newly-created scope. This is a change in behavior as it previously returned a scope in both cases([#45](https://github.com/opentracing/opentracing-ruby/pull/45)). See [Issue #41](https://github.com/opentracing/opentracing-ruby/issues/41).
* Improved documentation for `log` and `log_kv` …
=> Update changelog and version for 0.5.0 release
